# Plugin Definition below. This is essentially a valid helm values file that will be merged
# with the other vcluster values during vcluster create or helm install.
plugin:
  container-resources-sync:
    image: quay.io/spectrocloud-labs/vcluster-container-resource-upsync-plugin:v0.0.1
    imagePullPolicy: IfNotPresent